export const LOADING = "LOADING";

export const GET_DOGS = "GET DOGS";
export const GET_DOGS_API = "GET DOGS API";
export const GET_DOGS_DB = "GET DOGS DB";
export const GET_DOGS_AZ = "GET DOGS AZ";
export const GET_DOGS_ZA = "GET DOGS ZA";
export const GET_DOGS_NAME = "GET DOGS NAME";
export const GET_DOG_ID = "GET DOGS ID";
export const GET_DOGS_MORE = "GET DOGS MORE";
export const GET_DOGS_LESS = "GET DOGS LESS";
export const CREATE_DOG = "CREATE DOG";
export const DELETE_DOG = "DELETE DOG";

export const GET_TEMPERAMENTS = "GET TEMPERAMENTS";
export const GET_DOGS_TEMPERAMENT = "GET DOGS TEMPERAMENT";

export const SET_CURRENT_PAGE = "SET CURRENT PAGE";

export const CHANGE_OPTION_FILTER = "CHANGE OPTION FILTER";
export const CHANGE_VALUE_FILTER = "CHANGE VALUE FILTER";

export const CHANGE_THEME = "CHANGE THEME";

export const ADD_FAVOURITE = "ADD FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE FAVOURITE";

export const CREATE_COMMENT = "CREATE COMMENT";
export const GET_COMMENTS = "GET COMMENTS";

export default {
  LOADING,
  GET_DOGS,
  GET_DOGS_API,
  GET_DOGS_DB,
  GET_DOGS_AZ,
  GET_DOGS_ZA,
  GET_DOGS_NAME,
  GET_DOG_ID,
  GET_DOGS_MORE,
  GET_DOGS_LESS,
  CREATE_DOG,
  DELETE_DOG,
  GET_TEMPERAMENTS,
  GET_DOGS_TEMPERAMENT,
  SET_CURRENT_PAGE,
  CHANGE_OPTION_FILTER,
  CHANGE_VALUE_FILTER,
  CHANGE_THEME,
  ADD_FAVOURITE,
  REMOVE_FAVOURITE,
  CREATE_COMMENT,
  GET_COMMENTS,
};
